remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme 
title: [The website of LPZ]
description: [The website is used for y DS study]
show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
google_analytics: [Your Google Analytics tracking ID]